### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by todak2000**
## Description
Please include a summary of the change and relevant motivation and context. 
List any dependencies that are required for this change.

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes #(issue number 1) #(issue number 2 if applicable)

## How Has This Been Tested?
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to see how your change affects other areas of the code etc.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Stephen-Kamau — APPROVED** [review]
Good job for updates

**Review by byruzyayandy1 — APPROVED** [review]
Nice Updates

**Review by AminuIsrael — APPROVED** [review]

**Review by byruzyayandy1 — APPROVED** [review]
Weldone

**Review by albert85 — APPROVED** [review]
LGTM

**Review by albert85 — CHANGES_REQUESTED** [review]
@todak2000 , Please clear the codacy

**Review by byruzyayandy1 — APPROVED** [review]

**Pull request closed without merging**
